# Generated by Django 3.2 on 2022-08-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='first_presentation_date',
        ),
        migrations.AddField(
            model_name='award',
            name='first_awarded_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personnomination',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='people_nominations', to='cinema.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('science_fiction', 'Science-Fiction')], max_length=255),
        ),
    ]
