# Generated by Django 3.2 on 2022-08-17 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20220811_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('is_winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='personnomination',
            name='award',
        ),
        migrations.RemoveField(
            model_name='personnomination',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='personnomination',
            name='person',
        ),
        migrations.RemoveField(
            model_name='award',
            name='first_awarded_year',
        ),
        migrations.RemoveField(
            model_name='award',
            name='popular_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.DeleteModel(
            name='MovieNomination',
        ),
        migrations.DeleteModel(
            name='PersonNomination',
        ),
        migrations.AddField(
            model_name='nomination',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cinema.award'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='cinema.movie'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='cinema.person'),
        ),
    ]
