# Generated by Django 3.2.14 on 2022-07-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('winner', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='cinema.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('winner', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='cinema.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
